### ISSUE TITLE
NERSC Shifter requires removal of RPATH and updates to ld.so.conf

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#787] opened 2023-11-22 18:37 UTC
To use containers on NERSC through shifter we need to build our own MPI and allow NERSC to manipulate the LD_LIBRARY_PATH under the hood.   The only catch for Amanzi (and ATS) is that we have been explicitly including RPATH information to ensure we were linking to the correct third party libraries, and not inadvertently picking up a system library that was built with incompatible options or an incompatible version. 

Here we need to add an option to bootstrap.sh to control this behavior, and we need to update the Docker file to manage the system level library search (i.e., /etc/ld.so.conf) to ensure we are still getting the right TPLs and Amanzi libraries while allowing LD_LIBRARY_PATH to capture the NERSC MPI.  On the RPATH side this is likely just an if-else-then wrapped around CMAKE RPATH options.  For the ld.so.conf, we need to add our TPLS and Amanzi path information, but not anything about MPI.

**Comment by jd-moulton** [comment] 2023-11-28 17:09
I'll add more details for each of the convoluted (think band aids on duct tape) features of the linux gnu tool chain that make this a non-issue now.  Essentially, things just work, but understanding why they just work is important and revolves around the deprecation of RPATH in favor of RUNPATH, the differences in priority and behavior of RPATH and RUNPATH, and the fact that while we thought we were manipulating RPATH (since that what the CMAKE and compiler options state), we were in fact manipulating the RUNPATH.     Since LD_LIBRARY_PATH has precedence over RUNPATH, the NERSC approach works with our current docker images.

**Comment by rfiorella** [comment] 2024-03-17 23:01
@jd-moulton should we close this issue now since these containers are picking up paths correctly in shifter?

**Comment by rfiorella** [comment] 2024-03-29 04:09
The manual page for ld.so specifies the order in which shared libraries are linked. Currently:
1. RPATH (deprecated)
2. LD_LIBRARY_PATH
3. RUNPATH
4. /etc/ld.so.cache
5. system defaults (/lib and /usr/lib or /lib64 and /usr/lib64).

The ultimate issue here is that whether *_RPATH calls in CMake are applied to RPATH or RUNPATH is determined by the linker. Some (most?) modern linkers now currently will apply link using RUNPATH unless `--disable-new-dtags` is invoked, which will force CMake to use RPATH. If `--enable-new-dtags` is used (or is the default), *_RPATH in CMake will be applied to RUNPATH. 

Therefore, nothing really needed to be done for this ticket since what we thought CMake was applying to RPATH (based on the CMake *_RPATH vars) was actually being applied to RUNPATH. The reprioritization that we thought needed to be done to move these RPATH variables below LD_LIBRARY_PATH in priority therefore was already done by this potentially unexpected behavior in CMake.

A few references: 
https://stackoverflow.com/questions/52018092/how-to-set-rpath-and-runpath-with-gcc-ld
https://gitlab.kitware.com/cmake/cmake/-/issues/24648
https://gitlab.kitware.com/cmake/cmake/-/issues/25683

**Closed** 2024-03-29 04:09 UTC
Labels: Perlmutter, Containers
