### ISSUE TITLE
Residual-based control of convergence in NKA

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#280] opened 2019-01-27 21:35 UTC
Residual-based error control does not work correctly in the NKA when a PK calculates the maximum error. I see two solutions.  (1) Residual is available in the NKA and we can calculate its norm, either L2 or maximum.  (2) Pass additional control variable to PK via fn_->ErrorNorm(...) interface and let PK to decide how to calculate the error. 

I am leaning towards (1), which is the minimum intrusion solution.

**Comment by lipnikov** [comment] 2019-02-02 18:58
Looks like everyone is agree with me...

**Comment by jd-moulton** [comment] 2019-02-02 19:38
It makes sense that this is a problem with the current design.  I think we need to think about what happens when NKA is solving a system defined across multiple PKs.   So the PK that NKA is working directly is really an MPC with is pulling together information from multiple PKs.   Scaling of different quantities is likely going to be managed by the MPC, but what interface is best for it to use to handle these questions may also be best for it to provide to NKA as well.

**Comment by ecoon** [comment] 2019-02-22 13:55
Sorry for not responding -- I read this and didn't quite understand it.  The issue is that you want L2 norms of the error or some other quantity for error control?

David's comment is the key issue here -- scaling across PKs is rarely even.  Internally we calculate and log L2 norms on all ATS PKs, it would be pretty straightforward to return std::tuple<double,double> or a more general struct.  It doesn't affect much ATS code to change that part of the interface (we only have a few PKs that implement ErrorNorm, most all are based on a conserved quantity).

**Comment by lipnikov** [comment] 2019-02-22 17:03
One angle: residual is a well defined quantity, r  = F(u), regardless of PK structure.

**Comment by lipnikov** [comment] 2019-02-22 17:06
Another angle: MPC PK could be a linear operator, then NKA acts as GMRES and proper scaling of a preconditioned residual is provided by the preconditioner

**Comment by lipnikov** [comment] 2019-02-22 17:08
Anyway, now there is no much difference between varied monitor options ehich is not correct. I prefer larger variety of vitriol’s including casual linear algebra controls that are PK independent

**Comment by ecoon** [comment] 2019-02-22 20:26
a larger variety of what?

I'm fine with having options.  

After looking at the code, I do agree that our current set of monitoring options are pretty odd choices of names/algorithms.  I would expect something like:

* `MONITOR_RESIDUAL` just worked on r, applying an Linf norm with no filter through ErrorNorm()
* `MONITOR_UPDATE` (do we even need preconditioned update?) just worked on du, applying an Linf norm with no filter through ErrorNorm()
* `MONITOR_CUSTOM_ERROR` or some other new enum should pass r to `ErrorNorm(u, r)` and use what it gets back.

Is there ever a time we want to give the PK du, as in `ErrorNorm(u, du)`?  I guess we could add a `MONITOR_CUSTOM_UPDATE` or something like that?  I wouldn't use it at this point.

**Comment by ecoon** [comment] 2019-02-22 20:38
Is the issue then that for all of these you want both Linf (to check for convergence) and L2 (to do adaptive time step sizes based on error control)?

Then if you want both L2 and Linf norms of each of these things, it is easy to get all but the custom ones (as you noted).  I guess I would lean toward asking `ErrorNorm()` to return a std::tuple<double,double> of L2 and Linf norms.  If you're going to ask for both Linf and L2, you want to do them at the same time instead of repeating the calculation twice.

**Comment by lipnikov** [comment] 2019-02-22 20:51
Agree. My immediate goal is L2 norm for residual or preconditioned residual.

**Comment by ecoon** [comment] 2019-02-25 15:10
Sounds good.  I'm not asking you to do this, but it would be nice to have all of the nonlinear solvers updated with the same options.  I wonder if there is a better way to organize them to allow maintenance of these to be a bit easier.

**Comment by ecoon** [comment] 2019-05-07 13:31
Please don't commit code that changes answers without referring to the ticket that it is addressing, and definitely don't commit it with an error message of "minor cleaning of code."

Commit  b2c698bd9f82e09dd1fcece08902f12de0b047c4  addresses this ticket, and changes results.

**Comment by ecoon** [comment] 2019-05-07 13:48
Furthermore, this commit didn't do what (I thought) we agreed upon, which was to add more options and make the default stay the same.  To be clear, ATS uses "monitor residual" and ErrorNorm() in tandem, and this commit removed that as an option silently.

Furthermore, I think it is largely useless for a code solving a conservation equation.  It allows the solve to happily converge while not solving the conservation equation.  "monitor residual" is physically meaningless with the current change, and I can happily give you examples of Richards equation where this simply returns junk "solutions" even with very small nonlinear tolerances.  Taking the L2 of the error in mass conservation, then dividing by the L2 of the pressure at large pressures (what is done [here](https://github.com/amanzi/amanzi/blob/master/src/solvers/SolverNKA.hh#L230) is a meaningless quantity that is entirely dependent on units, etc.

Nearly all reactive transport codes (FEHM, PFLOTRAN, ATS) use a mix of an absolute and a relative norm.  Pressure changes are meaningless, instead we monitor the error in mass conservation, relative to some measure of small water content.  If Amanzi is currently using NKA with "monitor residual" I have no idea what your tolerances mean, and I definitely don't believe that mass conservation is enforced.

**Comment by ecoon** [comment] 2019-05-07 14:01
For example, see the surface flow problem below, which solves the diffusion wave equation on a simple ramp.  Rain falls on the domain, then turns off at 60 minutes.  The correct solution, with a nonlinear tolerance of 1.e-10, using the norm:

$error = L_inf ( \frac{ | r | \Delta t }{ max ( \rho h V, \rho V .001 ) }$

where $r$ is the residual (or error in mass conservation rate), $\rho$ the density, $h$ the ponded depth, $V$ the cell volume, and $.001$ is a "small" amount of water (1 mm) for absolute tolerances.  The units of this thing are then nondimensional, and can be compared to a tolerance.  This error norm results in the first solution for total integrated water content (right) and hydrograph out the bottom of the ramp (left).

<img width="1032" alt="Screen Shot 2019-05-07 at 9 50 48 AM" src="https://user-images.githubusercontent.com/5126139/57305411-0a8b4d80-70af-11e9-883d-82ab52bd3c2a.png">

The second solution shows what you get when you use NKA and the current default "monitor residual" option.  Effectively the solve "converges" in 0 iterations even with a tolerance of 1e-10 because the amount of water is small, and dividing errors in that water by a large pressure value small / large, and is a meaningless comparison that is dimension dependent.  Unless you nondimensionalize all of your conservation equations, this problem is always present.

<img width="1047" alt="Screen Shot 2019-05-07 at 9 51 21 AM" src="https://user-images.githubusercontent.com/5126139/57305424-1119c500-70af-11e9-90db-6ede234156d5.png">

**Comment by ecoon** [comment] 2019-05-07 14:11
Finally, the current norm completely negates the point of using an unstructured mesh.  By not considering the cell volume in your norm, you're "oversolving" large grid cells because they have larger water content (and therefore larger error in conservation), but the same pressure, as smaller cells.  So unstructured mesh solutions will be entirely dependent upon the error in big cells, and won't control error in small cells.

**Comment by lipnikov** [comment] 2019-05-07 14:12
It slipped through, b/c all tests passed. Please, be constructive and suggest a good test.

**Comment by lipnikov** [comment] 2019-05-07 16:08
> Finally, the current norm completely negates the point of using an unstructured mesh.  

From an epistemological position, this is stretching the truth.

**Comment by ecoon** [comment] 2019-05-07 16:24
Thanks, much better.

> It slipped through, b/c all tests passed.  Please, be constructive and suggest a good test.
Sure, I get that.  I guess none of our tests use this option or provide an ErrorNorm()?  Do you provide one in your Richards_PK?

> > Finally, the current norm completely negates the point of using an unstructured mesh.
> 
> From an epistemological position, this is stretching the truth.

Solve `du/dt = f(x)` on a 1D unstructured mesh using a control volume approach.  Integrating over the volume results in a factor of the cell volume on both sides in the case of piecewise constant f and u.  What does the unstructured mesh do?  It simply masks the error in small grid cells by making the L2 of the error be dominated by the cell volume factor on large grid cells, no?  Sure, you might be better resolving the gradients in f with your unstructured mesh, but you're canceling out that resolution by not actually solving the system on those grid cells, no?  Am I missing something here?

**Comment by lipnikov** [comment] 2019-05-07 16:32
>  Am I missing something here?

Totally. Unstructured meshes form a huge class from quasi-uniform to graded to anisotropic. l2 works fine on quasi-uniform meshes. 

But you are raising a good point: Do we need a volume based scaling for a preconditioned solver or the preconditioner provides an adequate scaling?

**Comment by ecoon** [comment] 2019-05-07 17:46
There are two considerations -- volume and scaling across equations in a multi-physics case.

In the preconditioned linear solve case, assuming you're then monitoring the correction (or the preconditioned residual, which is typically, units/magnitude wise, in the same range as the correction), then I agree that the preconditioner deals with the volumetric factor.  Assuming the primary variable units are comparable in magnitude for all block equations, then no special norm is needed.

If you're monitoring the residual itself, however, it doesn't, but I've never actually seen a code that monitored the residual and provided a custom norm for linear solves, thereby changing the search directions themselves.  I'm not sure what this would do, and I don't know if there is any theory about this.  I've always just monitored the correction (which is cheaper in, e.g. GMRES, where you get it for free, as opposed to monitoring the residual which requires another AllReduce()).  

The nonlinear solve is different.  Monitoring the correction in a nonlinear solve for reasonably nonlinear problems almost always sets you up to miss a case where the problem is weird and conservation is violated despite a small correction.  For instance, phase change in energy is a good example of this -- small temperature corrections may result in big energy changes, and monitoring the correction may still allow large energy conservation errors.  And just monitoring the L2 of the residual could, if you chose your units poorly, allow the energy residual to be swamped by the flow residual and/or not consider volume.  Using custom error norms for nonlinear solves allows us to get around the decision to not nondimensionalize everything from the start by nondimensionalizing in the error norm.

**Comment by lipnikov** [comment] 2019-05-07 20:06
Amanzi uses NKA to solve both linear and nonlinear systems and as such, it needs both custom error control and L2/l2 error control of some residual norm. I stepped back to the original custom error control and added l2 control of residual.

**Closed** 2021-04-13 20:59 UTC
